### ISSUE TITLE
Could not load filepaths/local

### ISSUE THREAD

**Issue by zzr525** [ebartrum/lightning_gan_zoo#1]
python run_network.py +expt=wgan dataset=mnist
Report Error:
/home/vin/.local/lib/python3.6/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive dataset/mnist.yaml in file:///home/vin/lightning_gan_zoo/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Could not load filepaths/local

**Comment by zzr525** [comment]
It seems lost filepaths directory. Where could I setting my "mnist_parent_directory", "filepaths.celeb_a_root" and "filepaths.celeb_a_sample_root"? Thanks

**Comment by ebartrum** [comment]
Apologies for not explaining this, have updated the README. Please pull latest version and then:

```cp conf/filepaths/example.yaml conf/filepaths/local.yaml```

Edit conf/filepaths/local.yaml with dataset locations on your system.

Please let me know if anything isnt clear!

**Comment by zzr525** [comment]
Thanks for your reply. I follow your guide and have two small issues. How to set "- submission_details: local" and " - override hydra/job_logging: disabled" in conf/config.yaml?

The first report issue is the same as before. We need to add "submission_details " in conf/filepaths/local.yaml:
Missing @package directive filepaths/local.yaml in file:///home/vin/lightning_gan_zoo/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Could not load submission_details/local

**Comment by zzr525** [comment]
The second report issue is about  " - override hydra/job_logging: disabled" (I try to remove or skip the - submission_details: local, and see this issue) :
/home/vin/.local/lib/python3.6/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive lr_scheduler/step_lr.yaml in file:///home/vin/lightning_gan_zoo/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Could not load override hydra/job_logging/disabled

**Comment by ebartrum** [comment]
> The second report issue is about " - override hydra/job_logging: disabled" (I try to remove or skip the - submission_details: local, and see this issue) :
> /home/vin/.local/lib/python3.6/site-packages/hydra/plugins/config_source.py:190: UserWarning:
> Missing @Package directive lr_scheduler/step_lr.yaml in file:///home/vin/lightning_gan_zoo/conf.
> See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
> warnings.warn(message=msg, category=UserWarning)
> Could not load override hydra/job_logging/disabled

I believe this is due to wrong hydra version. I have updated the README. Please try ```pip install hydra-core==1.1.0dev3```

**Comment by ebartrum** [comment]
> The first report issue is the same as before. We need to add "submission_details " in conf/filepaths/local.yaml:
> Missing @Package directive filepaths/local.yaml in file:///home/vin/lightning_gan_zoo/conf.
> See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
> warnings.warn(message=msg, category=UserWarning)
> Could not load submission_details/local

I've removed the requirement for submission_details file in the latest version. Please pull the latest version and try again

**Comment by zzr525** [comment]
Thanks for your help. It's can run, but there will be one issue after the first epoch.
like run  ‘python run_network.py +expt=wgan dataset=mnist’ or ‘python run_network.py +expt=gan_stability_r1 dataset=mnist’
![issue](https://user-images.githubusercontent.com/12869707/115140393-51508480-9ff4-11eb-9d95-2b82a3d7f564.png)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1800, 2400] at entry 0 and [3, 218, 178] at entry 2

**Comment by ebartrum** [comment]
OK, I'll try to solve this. Could you make a new issue for it? I'll mark the original issue closed.

**Comment by zzr525** [comment]
Thanks, I already make a new issue for it.
