### ISSUE TITLE
After the first epoch, report error 'RuntimeError: Caught RuntimeError in DataLoader worker process 0.'

### ISSUE THREAD

**Issue by zzr525** [ebartrum/lightning_gan_zoo#2]
There is one issue after the first epoch.
like run ‘python run_network.py +expt=wgan dataset=mnist’ or ‘python run_network.py +expt=gan_stability_r1 dataset=mnist’
![issue](https://user-images.githubusercontent.com/12869707/115156961-2a21a380-a044-11eb-9cec-870e41869154.png)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
data = fetcher.fetch(index)
File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
return self.collate_fn(data)
File "/home/vin/anaconda3/envs/pt18/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1800, 2400] at entry 0 and [3, 218, 178] at entry 2

**Comment by zzr525** [comment]
My MNIST dataset was downloaded by this.
https://github.com/pytorch/examples/blob/master/mnist/main.py

**Comment by zzr525** [comment]
Skip MNIST dataset, CelebA dataset can run.

**Comment by ebartrum** [comment]
Apologies for not clarifying this, FID calculation doesnt work on MNIST due to single channel output. I have updated the README to explain how to run without FID calculation. I also changed the default dataset to celeb_a.
